### ISSUE TITLE
Using the capacity website API returns incorrect number of nodes.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_grid#140]
When using the capacity.threefoldtoken.com API it returns the wrong number of nodes:
```
wget https://capacity.threefoldtoken.com/api/nodes
```
It always reports 100 nodes, while there should be much more.
When used to get the farmers overview
```
wget https://capacity.threefoldtoken.com/api/farmers
```
It returns the correct number of farmers.

**Comment by weynandkuijpers** [comment]
@zaibon Can you direct me to who can help me here?

**Comment by zaibon** [comment]
Yes, there have been a small change in the API of the directory. Because of the growing number of nodes in the grid returning the full dataset wasn't possible anymore. So the API is not paginated.

The maximum amount of node return in a single call is now set to a 100.  Next to that an extra header is set into the response. It is call page and the value represent the number of page for this request.
To get the full dataset you need to redo N number of time the same request by adding a query parameter specifying the page number.

Let's take an example:
```
 curl -I https://capacity.threefoldtoken.com/api/nodes
HTTP/2 200 
content-type: application/json
date: Fri, 20 Sep 2019 08:54:09 GMT
page: 10
server: Caddy
server: Werkzeug/0.14.1 Python/3.5.2
content-length: 67241
```
There we see that the number of page for this request is 10.
So we have to do 9 more requests to get the full dataset.
```
curl -I https://capacity.threefoldtoken.com/api/nodes?page=2
curl -I https://capacity.threefoldtoken.com/api/nodes?page=2
curl -I https://capacity.threefoldtoken.com/api/nodes?page=2
